### PR TITLE
Remove !important from AMP

### PR DESCRIPTION
**Pull request by ahmaxed**
Search console reported an issue regarding this

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
Looks good to me.

Tested locally on a copied version of the donation embed. Everything still hides on the `/amp` url as expected.

**Comment by ojeytonwilliams** [comment]
Silly question perhaps, but is there some source that's used to generate this?

**Comment by naomi-lgbt** [comment]
I believe Ghost comes with some AMP compliant CSS baked in, and we've layered some extra styling on top of that.

**Comment by ojeytonwilliams** [comment]
Okay.  Thanks, Nick.

**Pull request merged**
