### PR TITLE
feat: responsive bilibili embeds

### LINKED ISSUE #39437: embed bilibili video for Chinese publication articles
**Is your feature request related to a problem? Please describe.**
I can only add a video URL now.

**Describe the solution you'd like**
Could you add "embed bilibili video" to the editor? Thanks!

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Currently you can embed videos from Bilibili as HTML on Ghost, but they're not responsive. There's already some nifty code that goes through a post and appends some elements and styles to make them responsive. This PR just adds Bilibili to the list of video hosts the existing code looks for.

To embed a Bilibili video:

1. Get the `iframe` of the video you want to embed
2. In Ghost, click the plus button and click the HTML button to add custom HTML:
image
3. Paste the Bilibili `iframe` into the Ghost's HTML section

Then when you view the preview or publish the post, the Bilibili video will be responsive like other embedded videos from YouTube, Vimeo, and so on.

Here's a test post on .dev/news: https://www.freecodecamp.dev/news/p/8014c1e3-60d7-42be-88a9-a2cc29cb6842/

Fixes https://github.com/freeCodeCamp/freeCodeCamp/issues/39437

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
image

On a smaller screen I lose the player controls. Is that an issue on our end, or something with the Bilibili iframe?

**Comment by scissorsneedfoodtoo** [comment]
Hey @nhcarrigan, thanks for taking a look at this!

As far as I can tell that's just the way Bilibili videos behave. 

Another (unrelated) thing I noticed is that, even with the controls, videos max out at 360p. If you try to change it to 480 or 720, it just redirects you to the actual video page on Bilibili :man_shrugging:

Edit: Just checked on my phone and the controls are visible there:

image

They might be checking the device and show controls on smaller screens based on that.

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🎉 

The outstanding concerns I had seem to be related to Bilibili's iframe, not something under our control. 🙂

**Comment by scissorsneedfoodtoo** [comment]
Thanks for your thorough review, @nhcarrigan, and for the merge, @ahmadabdolsaheb.

I'll go ahead and deploy this now.

**Pull request merged**
