### PR TITLE
feat: lazy load images on /news

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Uses lazysizes to defer images loading until they will become visible.

### CODE REVIEW

**Comment by ahmaxed** [comment]
Should we also lazy load the author images?

**Comment by ojeytonwilliams** [comment]
We can, sure.  Should I add those changes in this PR?

**Comment by ahmaxed** [comment]
Sure, that makes sense.

**Review by ahmaxed — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
Actually, thinking about it, won't the author images always be above the fold?

That said, the rest of the images in the articles could be anywhere, so I'll take a look at them.

**Comment by ojeytonwilliams** [comment]
I can't see an obvious way to get at the images in an article, since they're buried inside `{{ content }}`.  @ahmadabdolsaheb @scissorsneedfoodtoo any ideas?  

I'm leaning towards deferring this to another PR, if that's okay.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, this looks good to me. LazySizes seems like a great, lightweight alternative to native lazy loading until Firefox and Safari catch up to Chrome's level of support.

For the author images, on the author page they'll always appear above the fold. But on the landing page and search results page, a good number will appear below the fold. Still, they're only 30x30 images, so lazy loading may not be totally necessary.

I'm thinking these changes can be merged as-is, and we can do the same for the search results page in another PR, and author images if we decide to do those as well.

For everything in `{{ content }}`, there doesn't seem to be an obvious way to do that. Ghost 4 apparently supports lazy loading for content images, but we would need to look at another solution for Ghost 3.

Someone used [Cloudflare Workers](https://stanislas.blog/2020/05/native-image-lazy-loading-ghost-cloudflare-worker/) to add `loading=lazy` to the images in posts.

Might be overkill for us now since we're planning to move to headless Ghost, but I'm sure we can figure out a good way to add the `lazyload` class with our SSG since we'll have the HTML for each post before building the page.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Comment by raisedadead** [comment]
> Ghost 4 apparently supports lazy loading for content images, but we would need to look at another solution for Ghost 3.

What matters is regardless of the Ghost version we use are this metadata available over the content API, when we consume that the data source for the JAMstack SSG that we use.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, that's true. Ghost 4 supports lazy loading images for article content, but only if Ghost is serving the pages.

For the JAMstack SSG we'd need to figure out another solution ourselves no matter what Ghost version we're on.

**Pull request merged**
