### PR TITLE
fix: bump number of en articles

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Related to https://github.com/freeCodeCamp/freeCodeCamp/pull/44149

### CODE REVIEW

**Review by naomi-lgbt — DISMISSED** [review]
Looks good to me!

**Comment by scissorsneedfoodtoo** [comment]
Sorry all, big oversight here. 

Because the News Theme is using full strings and fallbacks in a lot of places, the actual string in the search bar needs to be update, along with the keys in the other locale.json files.

This should be good to go now.

**Review by majestic-owl448 — APPROVED** [review]

**Comment by ojeytonwilliams** [comment]
> Because the News Theme is using full strings and fallbacks in a lot of places, the actual string in the search bar needs to be update, along with the keys in the other locale.json files.

Not that it's relevant for this PR, but can we change to something like `/learn`'s approach?  After all, the keys should rarely change.

**Comment by naomi-lgbt** [comment]
Probably not a bad idea, tbh.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, yes, I agree. I'd like to move over to using generic keys like we do on `/learn`. We're already doing that with 11ty, and it's always a bit tricky to keep the two different formats synchronized.

**Review by naomi-lgbt — APPROVED** [review]
I'm fine with this as is - we should move to generic keys later on though

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for confirming @nhcarrigan.

Totally agreed. Would be better to avoid situations like this in the future. I'll work on backporting the keys we'll use in 11ty News to the Ghost theme when I get some time in the future.

**Pull request merged**
