### PR TITLE
fix: url parsing

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Modifies the social-row theme component to properly handle apostrophes
in post titles. Due to the nature of what ghost allows, I had to move
the onclick handling to the script tags instead.

If there's a better approach, I'm definitely open to suggestions.

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb Could you QA this and if it looks good merge and deploy it?

**Comment by ahmaxed** [comment]
Is the issue associated with a specific browser? @nhcarrigan, were you able to reproduce the issue with the social cards locally? I have been able to tweet with and without the fix.

Note: the logged string in the console is the title.

Screen Shot 2021-01-31 at 4 41 32 PM
Screen Shot 2021-01-31 at 4 42 35 PM

**Comment by naomi-lgbt** [comment]
I was able to reproduce the issue locally and on `/news` - using Chrome, specifically.

**Comment by ahmaxed** [comment]
hmm, I tested it using chrome as well.

@scissorsneedfoodtoo, could you take a look and let me know if you could reproduce this locally?

**Comment by scissorsneedfoodtoo** [comment]
@nhcarrigan, thanks for handling this. I tested the current master locally in Chrome and Firefox and get this error whenever there's an apostrophe in the title. I can confirm that this fix works for those articles. 

Seems like translation helper included with Ghost doesn't handle certain punctuation as expected.

I think handling the buttons with a separate click handler is totally fine. The only thing I noticed is that we'll need to handle the Twitter message for other languages.

I played around with it a bit locally and Handlebars doesn't make it too easy -- turns out you can't pass JavaScript variables as parameters to the translate helper.

I think the easiest way might be to translate the first part of the message, "Thank you {twitter} for writing this helpful article", and include it as a key in the locale JSON files. Then you can include the rest of the URL as a template string.

**Comment by naomi-lgbt** [comment]
Sure thing - I'll explore that today and see if I can resolve it. :)

**Comment by naomi-lgbt** [comment]
Okay @scissorsneedfoodtoo, when you have time, I've modified this to translate the `Thank you for writing this article` text, passing the `twitter` value as a placeholder.

Because we hide the social row on the `zh-cn` locale, I did not update that translation map to reflect these changes. If I need to do so, let me know. :)

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for making those updates @nhcarrigan. Tested locally and everything LGTM :+1: :+1: 

And I think it's fine to leave it out of the zh-cn.json file. It doesn't seem to cause any errors, and I believe the translation helper just falls back to whatever the original string is if it doesn't exist in a locale's file. Not an issue since we're hiding that bit like you mentioned.

Will merge and deploy this now.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Pull request merged**
