### PR TITLE
fix: separate config and footer links from translation files

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
I tried to move as much out of the locale.json translation files as possible. It's not perfect, and there's still some HTML in the JSON files, but hopefully less will break now.

Unfortunately JSON is not allowed to be served from the `assets` directory, so I had to change everything to JavaScript objects and include them in `default.hbs`.

### CODE REVIEW

**Comment by raisedadead** [comment]
Related issue on this: https://github.com/freeCodeCamp/freeCodeCamp/issues/41142

**Comment by naomi-lgbt** [comment]
I pulled this down locally and everything looks correct - when I apply the theme to Ghost, it loads correctly but gives me this warning:

image

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching that @nhcarrigan :+1: :+1: I missed that because I was using the `npm run develop` workflow.

I'll take a look at that and make the appropriate updates.

**Comment by scissorsneedfoodtoo** [comment]
Okay, this should be ready for another round of review.

Unfortunately the `{{assets}}` helper only takes simple strings for the path. In the end, the best way I found to dynamically load the config objects for each language was with `import()` inside `async` functions.

If there's an easier/cleaner way to do this, just let me know.

**Comment by ojeytonwilliams** [comment]
Hey Kris, just to clarify, what we want to do is: display different links on the footer, but not use `/locales` because those files will be translated. Is that right?

> Unfortunately the {{assets}} helper only takes simple strings for the path. In the end, the best way I found to dynamically load the config objects for each language was with import() inside async functions.

Could [subexpressions](https://handlebarsjs.com/guide/expressions.html#subexpressions) help?  If we defined a helper that generated a language specific path, then would that make `assets` happy?

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, yes, that's what I'm thinking. Each footer will have different trending links and text updated at different times. And we should probably translate the text for each link in-house so we have a bit more control over the line length, and can prevent them from overflowing.

I left the other footer link text in `translation.json` for now like on the main repo, but we could move it to `assets/[lang]/footer.json` if we want to have a bit more control over those. The only thing is that there's a brief flash when the page loads and the script populates those elements.

It doesn't seem like `assets` works with subexpressions, at least in my testing. I tried things like `<script src="{{asset (concat 'config' site.lang 'footer.js' separator='/') }}"></script>`, but that would just throw the `[default.hbs] path.match is not a function` error. I might be using that wrong, though.

Update: This will need a bit of extra work to figure out a way to bust the cache every time we update these files.

Also, I should mention that the flash that happens is probably because the text for the trending articles is not handled by Handlebars, but is being set after the page loads. I think it happens whether or not we use `import()`. Sorry for the miscommunication.

**Comment by ahmaxed** [comment]
Thanks for the pr, @scissorsneedfoodtoo.

Tested locally, and pushed to english production.

We are definitely hitting some limits with handlebars that might affect scaling and maintenance.
It might be a good time to go headless instead.

**Pull request merged**
