### PR TITLE
fix: search bar functionality

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
This PR changes the listener for the search bar to `input`, which should fire for both mouse and keyboard input.

It also rearranges things a bit to prevent a race condition between `searchQuery` being updated and showing the footer.

Could you take a look at this if you get a chance @ojeytonwilliams?

Edit: Ended up widening the scope of this PR to try and bring it to parity with the Learn search bar.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey Kris, sure thing.  I might be doing something wrong, but if I enter in 'a' I see the results I expect, but clicking on the magnifying glass does nothing.  Pressing enter, however, takes me to http://localhost:2368/search/?query=a as expected.

I'd be happy to look into this, but could you tell me what I should expect to see?  

Also, do you know an easy way to recreate the race-condition so I can check that?

**Comment by scissorsneedfoodtoo** [comment]
Hey @ojeytonwilliams, awesome, thanks for catching that issue, too. 

Turns out I was a bit too aggressive with resetting the `hits` variable when the dropdown closes. Unlike on the main platform, with the library we're using here, the dropdown closes whenever you click the magnifying glass. 

I found some other inconsistencies with this search bar and the one on Learn. Now there's almost at parity (though I notice that using the up and down keys on Learn aren't working at the moment).

With these changes, here's how the magnifying glass button should work on both platforms: When you click or tab-select the button, it should trigger a search for the query in the input and take you to the search results page. It should work this way even if you select an article with the up and down arrows or tab.

For the race condition, I believe it's because the default behavior for this Algolia library is to quickly show the dropdown with the same hits if the search term is the same. So it wouldn't happen in most cases, but would if you, say, paste in the term "test", highlight and cut it, then paste it in again.

In that case, the current implementation would show undefined for `searchQuery` because the dropdown is rendered before that variable can be updated.

To test this, I just logged `searchQuery` around these places on the master branch: [#1](https://github.com/freeCodeCamp/news-theme/blob/11f0d046038ad37567a9b113e7181fa6db4de810/partials/algolia-search.hbs#L91), [#2](https://github.com/freeCodeCamp/news-theme/blob/11f0d046038ad37567a9b113e7181fa6db4de810/partials/algolia-search.hbs#L69)

**Review by moT01 — DISMISSED** [review]
I tried taking a look at this. Here's what I noticed:

Maybe a minor bug: If you type a query with zero results, you can hover the "No Tutorials Found" with your mouse and press enter to get taken to the results of the query.

Not related to this PR:

I think the up and down arrow keys are working on /learn, there just isn't a highlighting effect. You can type a query, then press down and then enter and get taken to the first article. So probably just need to get the background highlights to work.

Screen Shot 2021-01-14 at 5 46 10 PM

A few more observations - not necessarily problems:
The font and font-weight are different - this seems to be unique to firefox - maybe it's something on my end
The search box is smaller on learn
The text is slight off center vertically on news - this one is also unique to firefox.

I don't think any of these need to be fixed with this PR. Just my findings. LGTM 🎉 if we want to merge it.

**Comment by ahmaxed** [comment]
> Maybe a minor bug: If you type a query with zero results, you can hover the "No Tutorials Found" with your mouse and press enter to get taken to the results of the query.

It  happens on production, but That seems to be a pre-existing issue. 


> For the race condition, I believe it's because the default behavior for this Algolia library is to quickly show the dropdown with the same hits if the search term is the same. So it wouldn't happen in most cases, but would if you, say, paste in the term "test", highlight and cut it, then paste it in again.

This is resolved in this iteration.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, thank you for taking such a deep dive into this, especially that bit about hovering over "No tutorials found" and submitting a bad search query. I wasn't even aware of that bug.

Turned out to be a quick fix. I'll push up another commit in a moment.

About the centering issue, they appear about the same to my eyes, though I'm only working with 1080p screens. It's possible that it's a resolution / scaling issue that we've had in the past. 

One thing that sticks out is that the placeholder color is much more muted on Firefox both on News and Learn. I'll see if I can normalize that as well.

**Comment by ahmaxed** [comment]
shipped.

**Pull request merged**
