### PR TITLE
feat: split up article translation

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Modifies the articles within the translation files to separate the link
and title fields. The template then handles generating the `a` elements
within the handlebars template.

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

### CODE REVIEW

**Comment by moT01** [comment]
Could we turn this into an array and loop over it like you did on https://github.com/freeCodeCamp/freeCodeCamp/pull/40672 @nhcarrigan?

**Comment by naomi-lgbt** [comment]
I wasn't able to find an approach for that - Ghost themes appear to use Handlebars, but don't support custom helper functions and there isn't a built-in loop method.

I poked at it for a while with no luck.

**Comment by naomi-lgbt** [comment]
Ideally, this also shouldn't be merged until #42 is merged (I'll rebase with the new links after)

EDIT: #42 has been merged and I've rebased this.

**Comment by moT01** [comment]
It does look like you could possibly [loop over an array with handlebars](https://handlebarsjs.com/guide/builtin-helpers.html#each) - not sure if that would work with this - but, even if we could get that working - how much is it saving us? Might even make it more difficult to understand, so I'm fine with it like this.

**Comment by naomi-lgbt** [comment]
I've tried poking with that, but it doesn't want to cooperate. 

Ghost also offers a `forEach` helper, but that seems to be intended for their integrated data (like posts). Additionally, the `t` translation tool is baked in to Ghost and I believe that's applying limitations as well.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for your patience @nhcarrigan. Thanks for taking the time to update all these footer links! It's much cleaner now, even if we can't loop through the links like on Learn.

Hope you don't mind, but I pushed a couple of fixes for some minor things I noticed while testing locally. Could someone take another look and confirm that everything looks good?

**Comment by naomi-lgbt** [comment]
Heya @scissorsneedfoodtoo,

Commit a486c58 seems to revert the English links to the last selection of news articles instead of our current batch - is this accurate? Or am I missing something?

**Comment by scissorsneedfoodtoo** [comment]
Hi @nhcarrigan, I think some wires got crossed somewhere, but the English articles in this PR should be the latest ones from this PR: https://github.com/freeCodeCamp/news-theme/pull/38/files

**Comment by naomi-lgbt** [comment]
Yep - looks like I crossed my wires there. Thanks for clarifying 😅

**Review by ahmaxed — APPROVED** [review]

**Comment by ahmaxed** [comment]
shipped on english.

**Pull request merged**
