### PR TITLE
feat: add meta description for lighthouse

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
I pulled this down locally and it looks like this successfully injects the excerpt as the meta description, whether it's manually set by the author or the default excerpt. Does this need anything before it's ready to merge?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for checking on this @nhcarrigan. I was going to wait for confirmation about whether or not we always want to use the excerpt as the meta description.

I'm thinking that it's okay to go forward with this. We try to remove custom meta descriptions and titles before publishing now, and we'll always use the defaults when we move to headless Ghost.

**Review by naomi-lgbt — APPROVED** [review]
I'm good with this then. Should result in a bit of an increase on Lighthouse and won't break existing functionality.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

The only weird thing I discovered is that you can *also* set the meta description inside post settings and you'll end up with two descriptions.  It seems authors typically don't mess with the meta description, but it might be worth warning them not to.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, that's interesting. Does it also create a new `<meta name="description" content="...">` tag? Or is it a `<meta property="og:description" content="...">` type of tag?

**Comment by ojeytonwilliams** [comment]
@scissorsneedfoodtoo if you set the meta description you get a second `<meta name="description" content="whatever you entered">`, but not a second `<meta property="og:description">`

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for confirming that @ojeytonwilliams.

I can modify an old script to check for custom meta titles/descriptions and remove them, and update the News Style guide to include a note about leaving those blank.

**Pull request merged**
