### PR TITLE
fix: continue reading typo

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
Dumb question: how come this typo isn't visible on /news?  Has the previous commit not been deployed?

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for the quick review and merge @ojeytonwilliams.

Once I noticed the typo, I deployed a quick fix, then submitted this PR. Should be the other way around, but I figure it was such a minor change.

**Comment by ojeytonwilliams** [comment]
No, no it's fine. I just didn't understand, so thanks for the explanation!

**Pull request merged**
